FROM centos:8

# Install required packages
RUN yum update -y && yum install -y \
    epel-release \
    openssh-clients \
    sshpass \
    git \
    python3 \
    python3-pip \
    gcc \
    openssl-devel \
    libffi-devel \
    && yum clean all \
    && rm -rf /var/cache/yum/*

# Upgrade pip and install Ansible Runner
RUN pip3 install --upgrade pip && pip3 install ansible-runner

# Set the working directory to the root of the playbook
WORKDIR /opt

# Copy the Ansible playbook and inventory to the container
#COPY playbook.yml inventory.ini ./
RUN git clone $GIT_URL

# Run the playbook using Ansible Runner
CMD ansible-runner run --playbook playbook.yml --inventory inventory.ini
